Enable multi-column matches in clean_spelling_vars() with .regex keyword
reconhub/linelist pull request #98
Opened 2019-10-15 10:58 UTC by patrickbarks

Implements a `.regex` keyword in `clean_spelling_vars()`, per #40. For example, the wordlist variable `".regex ^lab_result_"` will match any column name beginning with "lab_result_". Any variable in the wordlist without a `.regex` keyword (or `.global`) will be matched literally, as in the current behaviour.

Simple example:
```
# create data
dat <- data.frame(
  id = formatC(1:10, width = 2, flag = "0"),
  site = sample(LETTERS[1:3], 10, replace = TRUE),
  lab_result_01 = sample(c(c("high", "low", "norm", "inc")), 10, replace = TRUE),
  lab_result_02 = sample(c(c("high", "low", "norm", "inc")), 10, replace = TRUE),
  lab_result_03 = sample(c(c("high", "low", "norm", "inc")), 10, replace = TRUE),
  stringsAsFactors = FALSE
)

# create wordlist
# key ".regex ^lab_result_" will match any column starting with "lab_result_"
wordlist <- data.frame(
  value = c("high", "low", "norm", "inc"),
  replacement = c("High", "Low", "Normal", "Inconclusive"),
  variable = rep(".regex ^lab_result_", 4),
  stringsAsFactors = FALSE
)

# compare original and cleaned data
head(dat)
head(linelist::clean_variable_spelling(dat, wordlist))
```
I've also added some corresponding documentation and tests. Happy to make edits to the PR if you have suggestions/requests.

2019-10-15 14:35 UTC, zkamvar requested changes
This is wonderful! Thank you for submitting this and running into a bunch of the hurdles that I didn't even think about. 

I like what you did. I was initially confused as to why we needed to_iterate_x and to_iterate_wordlist, but I understand it now since we need to keep track of the regex parts of the wordlist as well as the columns of the original data. 

Additionally, way to go on navigating the error and warning collection system that I had crudely hacked together! 

One suggestion I have is that we should bypass the regex acrobatics if there is no .regex keyword. I've highlighted the point where I think it should be in my review, but otherwise this is good work :)

2019-10-15 14:35 UTC, zkamvar commented on R/clean_variable_spelling.R
> +    is_var_regex <- grepl("^\\.regex", vars_check)
Two things:

1. At this point, I think it would be good to have a control structure to check if any of the vars contain the regex keyword. If the regex isn't present, then there's no need to perform any of this manipulation.
2. This grep could match a column called .regexam, so I'm suggesting an explicit space here
```suggestion
    is_var_regex <- grepl("^\\.regex[[:space:]]", vars_check)
```

2019-10-15 14:35 UTC, zkamvar commented on R/clean_variable_spelling.R
> +      function(j) names(x)[grepl(j, names(x), perl = TRUE)]
This will have the same effect

```suggestion
      FUN = grepl, 
      x = names(x), value = TRUE, perl = TRUE)
```

2019-10-15 14:35 UTC, zkamvar commented on R/clean_variable_spelling.R
> +    vars_regex_match_n <- vapply(vars_regex_match_list, length, 0L)
```suggestion
    vars_regex_match_n <- lengths(vars_regex_match_list)
```

2019-10-15 14:35 UTC, zkamvar commented on tests/testthat/test-clean_variable_spelling.R
> +  expect_true(all(df_clean$column_1 %in% d1$replace))
```suggestion
  expect_setequal(df_clean$column_1, d1$replace)
```

2019-10-15 14:35 UTC, zkamvar commented on tests/testthat/test-clean_variable_spelling.R
> +  expect_true(all(df_clean$column_2 %in% d1$replace))
```suggestion
  expect_setequal(df_clean$column_2, d1$replace)
```

2019-10-15 14:35 UTC, zkamvar commented on tests/testthat/test-clean_variable_spelling.R
> +  expect_true(all(df_clean$my_column %in% d2$replace))
```suggestion
  expect_setequal(df_clean$my_column, d2$replace))
```

2019-10-16 07:41 UTC, patrickbarks commented
Great, thanks for the review! I've made all the changes you recommended, plus some minor changes to the internal code documentation. I also made a minor change to the example for `clean_variable_spelling()`, such that the possible values for my `lab_result_` columns are `c('High', 'Normal', 'Inconclusive')` rather than `c('Positive', 'Negative', 'Inconclusive')`. The mix of positive and negative results for a given patient was bothering me :)

Also, I just realized that I mistakenly referred to `clean_spelling_vars()` in the PR title rather than `clean_variable_spelling()`. Sorry about that!

2019-10-16 09:19 UTC, zkamvar commented
> Great, thanks for the review! I've made all the changes you recommended, plus some minor changes to the internal code documentation. I also made a minor change to the example for `clean_variable_spelling()`, such that the possible values for my `lab_result_` columns are `c('High', 'Normal', 'Inconclusive')` rather than `c('Positive', 'Negative', 'Inconclusive')`. The mix of positive and negative results for a given patient was bothering me :)

Great! I'll have a look at the changes today. I'm fine with how you changed the examples (though I'm not as bothered by a mix of positive and negative test results assuming the tests are different).

> 
> Also, I just realized that I mistakenly referred to `clean_spelling_vars()` in the PR title rather than `clean_variable_spelling()`. Sorry about that!

No worries! FWIW, there should be a little "edit" button that you can use to update/fix your comment.

2019-10-16 09:42 UTC, zkamvar approved these changes

2019-10-16 09:43 UTC, zkamvar commented
Looks good to me! One more thing before you merge: would you mind adding your name to the authors line in the function documentation?

2019-10-16 10:39 UTC, merged

2019-10-16 10:39 UTC, zkamvar commented
Thank you!